// <auto-generated />
using System;
using DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataLayer.Migrations.Blog
{
    [DbContext(typeof(BlogContext))]
    [Migration("20210421174529_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("blog")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DataLayer.Models.Blog.BatchJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClassName")
                        .HasColumnType("text")
                        .HasColumnName("classname");

                    b.Property<string>("ContractJson")
                        .HasColumnType("text")
                        .HasColumnName("contractjson");

                    b.Property<string>("ContractName")
                        .HasColumnType("text")
                        .HasColumnName("contractname");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("startedat");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("StoppedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("stoppedat");

                    b.HasKey("Id")
                        .HasName("pk_batchjob");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_batchjob_status");

                    b.ToTable("batchjob");
                });
#pragma warning restore 612, 618
        }
    }
}
